version: "3"
services:
  e2e-tests:
    image: hydrofoil/hypertest:0.6.6
    network_mode: "host"
    environment:
      NODE_EXTRA_CA_CERTS: "/lndo.site.crt"
      BASE_URI: "https://cube-creator.lndo.site/"
    volumes:
      - ~/.lando/certs/lndo.site.crt:/lndo.site.crt
      - ./e2e-tests:/tests
