name: "Env setup"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"
    - run: yarn install --ci
      shell: bash
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@1.0.11
      with:
        docker_version: 20.10.20
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Start site
      uses: tpluscode/action-setup-lando@v0.1.4
      with:
        version: v3.11.0
        healthcheck: https://cube-creator.lndo.site/ping
        timeout: 30000
      env:
        DOCKER_BUILDKIT: "1"
