name: "Env setup"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2.4.0
      with:
        node-version: 16
        cache: "yarn"
    - run: yarn install --ci
      shell: bash
    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@1.0.8
      with:
        docker_version: 20.10.12
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Start site
      uses: tpluscode/action-setup-lando@v0.1.3
      with:
        version: v3.6.2
        healthcheck: https://cube-creator.lndo.site/ping
        timeout: 30000
      env:
        DOCKER_BUILDKIT: "1"
