name: Pipeline

on:
  workflow_dispatch:
    input:
      job:
        description: 'Job URL'
        required: true

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      TS_NODE_TRANSPILE_ONLY: "true"
      AUTH_RUNNER_CLIENT_ID: ${{ secrets.AUTH_RUNNER_CLIENT_ID }}
      AUTH_RUNNER_ISSUER: ${{ secrets.AUTH_RUNNER_ISSUER }}
      AUTH_RUNNER_CLIENT_SECRET: ${{ secrets.AUTH_RUNNER_CLIENT_SECRET }}
      GRAPH_STORE_ENDPOINT: ${{ secrets.GRAPH_STORE_ENDPOINT }}
      GRAPH_STORE_USER: ${{ secrets.GRAPH_STORE_USER }}
      GRAPH_STORE_PASSWORD: ${{ secrets.GRAPH_STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.2
        with:
          node-version: 14
      - run: yarn install --ci
      - run: yarn ts-node cli/index.ts transform --job "${{ github.event.inputs.job }}" --execution-url "https://${{ github.repository }}/actions/runs/${{ github.run_id }}" --to graph-store --debug
