name: Test pipelines

on: push

jobs:
  pipeline:
    strategy:
      matrix:
        command:
        - test:cli:transform
        - test:cli:publish
        - test:cli:import
        - test:cli:timeoutJobs

    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/setup-env
      - run: yarn ${{ matrix.command }}
        env:
          AUTH_RUNNER_CLIENT_SECRET: ${{ secrets.AUTH_RUNNER_CLIENT_SECRET }}
      - name: logs on fail
        if: ${{ failure() }}
        run: lando logs
      - name: Codecov
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
